[build]
  # Build command for the React/Vite app
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"
  
  # Enable experimental features if needed
  NODE_OPTIONS = "--max_old_space_size=4096"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Prevent caching of the main HTML file
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Redirects for legacy URLs or external integrations
[[redirects]]
  from = "/dashboard"
  to = "/ai-dashboard"
  status = 302

# Form handling (if you have contact forms)
[[forms]]
  name = "contact"

# Environment variables (set these in Netlify dashboard)
# VITE_API_URL = "your-api-url"
# VITE_APP_NAME = "TuniPark Dashboard"
